<script setup lang="ts">
import { ref } from 'vue'
import CoworkerFileTree from '../workflow/CoworkerFileTree.vue'
import LiveDiff from './LiveDiff.vue'

interface Props {
  sessionId: string
  currentTab?: 'report' | 'ppt' | 'file-diff'
}

const props = withDefaults(defineProps<Props>(), {
  currentTab: 'report'
})

// Mock preview content
const previewContent = ref(`# AI Agent 市场分析报告

## 执行摘要
本报告分析了当前AI Agent市场的主要趋势和竞争格局...

## 市场规模
- 2024年全球市场: $120亿美元
- 预计2026年: $350亿美元
- CAGR: 45%

## 主要竞品
1. **Manus** - 沙箱执行 + 计划背诵
2. **Coworker** - 本地文件深度操控
3. **GenSpark** - 深度研究引擎

## 差异化机会
- Vibe Workflow理念
- 三文件工作法
- 多模态能力整合

---
*Generated by TokenDance AI Agent*
`)
</script>

<template>
  <div class="preview-area">
    <!-- Report Tab -->
    <div v-if="currentTab === 'report'" class="preview-content">
      <pre class="markdown-preview">{{ previewContent }}</pre>
      <div class="preview-actions">
        <button class="btn-action">📥 下载</button>
        <button class="btn-action">📋 复制</button>
        <button class="btn-action">🔄 刷新</button>
      </div>
    </div>

    <!-- PPT Tab (Phase3) -->
    <div v-else-if="currentTab === 'ppt'" class="preview-content">
      <div class="ppt-placeholder">
        <span class="placeholder-icon">📊</span>
        <p>PPT预览功能将在Phase3实现</p>
      </div>
    </div>

    <!-- File Diff Tab -->
    <div v-else-if="currentTab === 'file-diff'" class="file-diff-view">
      <div class="file-diff-layout">
        <div class="file-tree-panel">
          <CoworkerFileTree />
        </div>
        <div class="diff-panel">
          <LiveDiff />
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.preview-area {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  position: relative;
}

.preview-content {
  flex: 1;
  padding: 24px;
  overflow-y: auto;
  background: var(--bg-secondary, rgba(28, 28, 30, 0.9));
}

.preview-content::-webkit-scrollbar {
  width: 8px;
}

.preview-content::-webkit-scrollbar-track {
  background: rgba(255, 255, 255, 0.05);
}

.preview-content::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.2);
  border-radius: 4px;
}

.markdown-preview {
  color: var(--text-primary);
  font-size: 14px;
  line-height: 1.8;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  white-space: pre-wrap;
  word-wrap: break-word;
}

.preview-actions {
  position: absolute;
  top: 16px;
  right: 16px;
  display: flex;
  gap: 8px;
}

.btn-action {
  padding: 8px 12px;
  background: rgba(28, 28, 30, 0.9);
  border: 1px solid var(--divider-color);
  border-radius: 6px;
  color: var(--text-primary);
  cursor: pointer;
  font-size: 13px;
  backdrop-filter: blur(10px);
  transition: all 120ms ease-out;
}

.btn-action:hover {
  background: rgba(0, 217, 255, 0.2);
  border-color: var(--color-node-active);
}

/* PPT Placeholder */
.ppt-placeholder {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
  color: var(--text-secondary);
}

.placeholder-icon {
  font-size: 64px;
  margin-bottom: 16px;
  opacity: 0.5;
}

.ppt-placeholder p {
  margin: 0;
  font-size: 14px;
}

/* File Diff View */
.file-diff-view {
  flex: 1;
  display: flex;
  overflow: hidden;
}

.file-diff-layout {
  flex: 1;
  display: flex;
  gap: 1px;
  background: var(--divider-color);
}

.file-tree-panel {
  width: 280px;
  flex-shrink: 0;
  background: var(--bg-primary);
  overflow: hidden;
}

.diff-panel {
  flex: 1;
  background: var(--bg-primary);
  overflow: hidden;
}

:root {
  --bg-primary: rgba(18, 18, 18, 0.95);
  --bg-secondary: rgba(28, 28, 30, 0.9);
  --text-primary: #ffffff;
  --text-secondary: rgba(255, 255, 255, 0.6);
  --divider-color: rgba(255, 255, 255, 0.1);
  --color-node-active: #00D9FF;
}
</style>
