"""Add Project-First architecture models

Revision ID: 66425cd35564
Revises: g9h0i1j2k3l4
Create Date: 2026-01-21 23:12:18.135072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66425cd35564'
down_revision: Union[str, Sequence[str], None] = 'g9h0i1j2k3l4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.Enum('research', 'document', 'slides', 'code', 'data_analysis', 'quick_task', name='projecttype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'completed', 'archived', name='projectstatus'), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('conversation_count', sa.Integer(), nullable=False),
    sa.Column('artifact_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.Enum('general', 'initial_draft', 'refinement', 'review', 'export', name='conversationpurpose'), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', name='conversationstatus'), nullable=False),
    sa.Column('selection_context', sa.JSON(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_table('project_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('change_type', sa.Enum('auto', 'manual', 'milestone', 'rollback', name='versionchangetype'), nullable=False),
    sa.Column('changed_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_versions_project_id'), 'project_versions', ['project_id'], unique=False)
    op.add_column('artifacts', sa.Column('project_id', sa.String(length=36), nullable=True))
    # Add version with server_default for existing rows
    op.add_column('artifacts', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('artifacts', sa.Column('parent_version_id', sa.String(length=36), nullable=True))
    # Add is_latest with server_default for existing rows
    op.add_column('artifacts', sa.Column('is_latest', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('artifacts', sa.Column('content_preview', sa.Text(), nullable=True))
    op.add_column('artifacts', sa.Column('word_count', sa.Integer(), nullable=True))
    op.alter_column('artifacts', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    op.create_foreign_key(None, 'artifacts', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'artifacts', 'artifacts', ['parent_version_id'], ['id'], ondelete='SET NULL')
    op.add_column('messages', sa.Column('conversation_id', sa.String(length=36), nullable=True))
    op.alter_column('messages', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.alter_column('messages', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('messages', 'conversation_id')
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.drop_index(op.f('ix_artifacts_project_id'), table_name='artifacts')
    op.alter_column('artifacts', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('artifacts', 'word_count')
    op.drop_column('artifacts', 'content_preview')
    op.drop_column('artifacts', 'is_latest')
    op.drop_column('artifacts', 'parent_version_id')
    op.drop_column('artifacts', 'version')
    op.drop_column('artifacts', 'project_id')
    op.drop_index(op.f('ix_project_versions_project_id'), table_name='project_versions')
    op.drop_table('project_versions')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
