"""add research_tasks table

Revision ID: e4929bd393e9
Revises: 2601d5d2aaaa
Create Date: 2026-01-19 16:54:03.672675

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'e4929bd393e9'
down_revision: str | Sequence[str] | None = '2601d5d2aaaa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
